fixing progress counter bug
datastax/cassandra-data-migrator pull request #197
Opened 2023-09-04 11:58 UTC by mieslep

1. Consolidates progress logging into helper class `JobCounter`
2. Separates counts within each thread from the global counts
3. Increments global counts as each thread completes
4. Introduces new parameter to enable per-part logging
5. Per-part logging on a single line per part

**Which issue(s) this PR fixes**:
Fixes #196

**Checklist:**
- [X] Automated Tests added/updated
- [X] Documentation added/updated
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2023-09-05 20:07 UTC, msmygit commented on SIT/regression/03_performance/migrate.properties
> +spark.cdm.perfops.printStatsAfter                 450
LGTM. Let's please coordinate with docs crew to publish this at https://docs.datastax.com/en/astra-serverless/docs/migrate/cassandra-data-migrator.html page

2023-09-05 20:07 UTC, msmygit commented on src/test/java/com/datastax/cdm/properties/PropertyHelperTest.java
> +        assertTrue(helper.meetsMinimum("a", 100L,0L));
```suggestion
        assertTrue(helper.meetsMinimum("a", 100L, 0L));
```

2023-09-05 20:07 UTC, msmygit commented on src/test/java/com/datastax/cdm/properties/PropertyHelperTest.java
> +        assertFalse(helper.meetsMinimum("a", 1L,100L));
```suggestion
        assertFalse(helper.meetsMinimum("a", 1L, 100L));
```

2023-09-05 20:07 UTC, msmygit commented on src/main/java/com/datastax/cdm/job/JobCounter.java
> +        printProgress(true);
I don't understand what we're doing in here by calling both `true` and `false`?

2023-09-05 20:10 UTC, msmygit commented
Any idea why we're receiving [these `ERROR`s](https://github.com/datastax/cassandra-data-migrator/actions/runs/6073955848/job/16476859913?pr=197#step:4:1129) in the build output and how do we address them?

2023-09-06 13:06 UTC, msmygit approved these changes

2023-09-07 12:48 UTC, pravinbhat requested changes

2023-10-25 19:06 UTC, msmygit commented
I've encorporated the review comments and pushed the changes. Merging here.

2023-10-25 19:07 UTC, merged