[ISSUE-51] Fix error in accessing config when running job in cluster mode
datastax/cassandra-data-migrator pull request #52
Opened 2022-12-20 08:12 UTC by abinaya21

2022-12-22 16:31 UTC, abinaya21 commented
@pravinbhat Could you please check why the build is erroring out on both of my PRs?

2023-02-03 23:57 UTC, pravinbhat requested changes
Changes look good. Make sure to pull the latest from main branch & merge the conflicts. 
Please also update the pom version to use 3.0.x format & the build should pass.

2023-02-06 07:13 UTC, abinaya21 commented
Have updated pom version and I see the build failing with the following error
<img width="1130" alt="Screenshot 2023-02-06 at 12 42 42 PM" src="https://user-images.githubusercontent.com/17826577/216907211-e5c46617-084c-4266-aeca-ba9f960d5c8d.png">

2023-02-07 04:59 UTC, pravinbhat approved these changes

2023-02-07 04:59 UTC, merged